### ISSUE TITLE
Cloud in front of sun looks like beginning of Old Cowboy with Mustache emoji. Please fix this.

### ISSUE THREAD

**Issue by anoopr** [nicolehe/nicole.pizza#2]
<img width="209" alt="image 2016-04-05 at 7 22 07 am" src="https://cloud.githubusercontent.com/assets/2140/14285150/3be1c018-faff-11e5-8171-763b0c173373.png">

See also: https://github.com/twitter/twemoji/issues/39

**Comment by nicolehe** [comment]
<img width="209" alt="cowboy" src="https://cloud.githubusercontent.com/assets/6288931/14285530/ec3a3fde-fb19-11e5-9b6b-85eb6d4cdad1.png">
Does this help with your problem?
